name: Publish NuGet Package

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  pack-and-publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

      - name: Restore
        run: dotnet restore

      - name: Determine Version
        id: version
        run: |
          DATE=$(date +'%Y.%m.%d')
            RUN=${GITHUB_RUN_NUMBER}
          VERSION="$DATE.$RUN"
          echo "Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Pack
        run: dotnet pack PowNet/PowNet.csproj -c Release -o out /p:PackageVersion=${{ steps.version.outputs.VERSION }} /p:ContinuousIntegrationBuild=true

      - name: Publish
        run: dotlet nuget push out/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
